<a href="https://colab.research.google.com/github/Najaf-14/Neural-Networking-and-DeepLearning/blob/main/ANN%26DL_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pickle

mylist = ["I", "am", 4, 13.327]

myfile = open("binary.dat", "wb")
pickle.dump(mylist, myfile)
myfile.close()

myfile = open("text.txt", "w")
myfile.write("My name is Najaf")
myfile.close()

myfile = open("text.txt")
print(myfile.read())
myfile.close()

myfile = open("binary.dat", "rb")
loadedlist = pickle.load(myfile)
myfile.close()

print(loadedlist)

My name is Najaf
['I', 'am', 4, 13.327]


In [ ]:
# Write
# myFile = open("najaf.txt", "w")
# myFile.write("I am practicing pickle for serializing and deserializing")
# myFile.close()

# Read
# myFile = open("najaf.txt", "r")
# print(myFile.read())

# Append
myFile = open("najaf.txt", "a")
myFile.write("\nI am Learning python")
myFile.close()

In [ ]:
import pickle

mylist = ["I", "am", "Najaf", 4, 13.327]

# write
myfile = open("najaf_binary.dat", "wb")
pickle.dump(mylist, myfile)

# read
myfile = open("najaf_binary.dat", "rb")
loadList = pickle.load(myfile)
print(loadList)

myfile.close()

['I', 'am', 'Najaf', 4, 13.327]


In [ ]:
# class Student:
#   def display(self):
#     print("Hello,")
#     print("I am Najaf.")

# std1 = Student()
# std1.display()

# class Person:
#   def __init__(self, name, age):
#     self.name = name
#     self.age = age

#   def Info(self):
#     print("Name: ", self.name)
#     print("Age: ", self.age)

# p1 = Person("Najaf", 21)
# p2 = Person("Ali", 22)

# p1.Info()
# p2.Info()

class Animal:
    def eat(self):
        print("Animal is eating")


class Dog(Animal):
    def bark(self):
        print("Dog is barking")


dog1 = Dog()

dog1.eat()
dog1.bark()

Animal is eating
Dog is barking


In [ ]:
class Student:
    def __init__(self):
        self.name = "Najaf"

    def print_name(self):
        print(self.name)


# student1 = Student()
# student2 = Student()

# student1.name = "Ali"

# student1.print_name()
# student2.print_name()

Student.name = "Sara"
print(Student.name)

s1 = Student()
s1.print_name()

Sara
Najaf


In [ ]:
import pickle

myList = ["I", "am", "Najaf", 4, 13.327]

file1 = open("file1.dat", "wb")
pickle.dump(myList, file1)
file1.close()

file1 = open("file1.dat", "rb")
load_file1 = pickle.load(file1)
file1.close()

print("Deserialized data:")
print(load_file1)

file2 = open("file2.txt", "w")
file2.write(str(load_file1))
file2.close()


Deserialized data:
['I', 'am', 'Najaf', 4, 13.327]


In [ ]:
import numpy as np

# print(np.__version__)

# list1 = [1,2,3,4,5,6]
# print(list1)
# print(type(list1))

# arr = np.array((1,2,3,4,5))
# print(arr)
# print(type(arr))

# arr = np.array(list1)
# print(arr)
# print(type(arr))

# list = [
#     [1,2,3],
#     [4,5,6]
# ]
# for num in list
#   for n in num:
#     print(n)

# 2D
# list1 = [1,2,3,4]
# list2 = [5,6,7,8]

# arr = np.array([list1, list2])
# print(arr)
# print(arr.ndim) # n dimension

# 3D
# list1 = [1,2,3,4]
# list2 = [5,6,7,8]
# list3 = [9,10,11,12]

# arr = np.array([[list1, list2, list3]]) # 3 square brackets
# print(arr)
# print(arr.ndim) # n dimension

arr = np.array([1,2,3], ndmin=5)
print(arr)
print("no of dimensions: ", arr.ndim)

[[[[[1 2 3]]]]]
no of dimensions:  5


In [4]:
# Attributes of numpy array
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

print("Shape: ", arr.shape)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)
print("No of Dimensions: ", arr.ndim)

[[1 2 3 4]
 [5 6 7 8]]
Shape:  (2, 4)
Size:  8
Data Type:  int64
No of Dimensions:  2
