<a href="https://colab.research.google.com/github/Najaf-14/Neural-Networking-and-DeepLearning/blob/main/ANN%26DL_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# print(np.__version__)

# list1 = [1,2,3,4,5,6]
# print(list1)
# print(type(list1))

# arr = np.array((1,2,3,4,5))
# print(arr)
# print(type(arr))

# arr = np.array(list1)
# print(arr)
# print(type(arr))

# list = [
#     [1,2,3],
#     [4,5,6]
# ]
# for num in list
#   for n in num:
#     print(n)

# 2D
# list1 = [1,2,3,4]
# list2 = [5,6,7,8]

# arr = np.array([list1, list2])
# print(arr)
# print(arr.ndim) # n dimension

# 3D
# list1 = [1,2,3,4]
# list2 = [5,6,7,8]
# list3 = [9,10,11,12]

# arr = np.array([[list1, list2, list3]]) # 3 square brackets
# print(arr)
# print(arr.ndim) # n dimension

arr = np.array([1,2,3], ndmin=5)
print(arr)
print("no of dimensions: ", arr.ndim)

[[[[[1 2 3]]]]]
no of dimensions:  5


In [ ]:
# Attributes of numpy array
import numpy as np

# arr = np.array([[1,2,3,4],[5,6,7,8]])
# print(arr)

# print("Shape: ", arr.shape)
# print("Size: ", arr.size)
# print("Data Type: ", arr.dtype)
# print("No of Dimensions: ", arr.ndim)

# Task
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print("Array 1:", arr1)
print("Shape: ", arr1.shape)
print("Size: ", arr1.size)
print("dType: ", arr1.dtype)
print("nDim: ", arr1.ndim)

print("Array 2:", arr2)
print("Shape: ", arr2.shape)
print("Size: ", arr2.size)
print("dType: ", arr2.dtype)
print("nDim: ", arr2.ndim)



In [ ]:
# Array methods
import numpy as np

zero_array = np.zeros((2,3))
print("Zero Array")
print(zero_array)

ones_array = np.ones((2,2))
print("Ones Array")
print(ones_array)

full_array = np.full((4,2), 8)
print("Full Array")
print(full_array)

identity_arr = np.eye(3)
print("Identity Array")
print(identity_arr)

print("Empty Array")
print(np.empty(2))

#evenly spaced array
print(np.arange(1,9,1)) # start=1, end<9, increment of 1
print(np.arange(1,9,2))

#specific no of values equally (spaced) between range
print(np.linspace(1,10,4)) # gap between each num is same

#random values(float)
# r_arr = np.random.rand(2,3)
# print(r_arr)

#int
r_arr = np.random.randint(1,10,(2,3))
print(r_arr)


In [ ]:
import numpy as np

# a = np.array([1,2,3])
# b = np.array([1,2,3])

# print(a + b)
# print(a - b)
# print(a * b)
# print(a / b)
# print(a ** b)
# print(a // b)

# a = np.array([[1,2,3], [4,5,6]])
# b = np.array([[1,2,3], [4,5,6]])

# print(a + b)
# print(a - b)
# print(a * b)
# print(a / b)

# matrix multiplication and dot product
# a = np.array([
#     [1, 2],
#     [3, 4]
# ])
# b = np.array([
#     [1, 2],
#     [3, 4]
# ])

# print(a @ b)
# print(np.dot(a,b))

# sparse matrix contains mostly zeros
matrix = np.array([
    [0, 0, 0, 5],
    [0, 0, 0, 0],
    [0, 3, 0, 0],
    [0, 0, 0, 0]
])
print(matrix)

In [ ]:
# Array Indexing & Slicing
import numpy as np

# arr = np.array([1,3,5,7,9])
# print(arr)

# print(arr[0])
# arr[1] = 100
# print(arr)
# print(arr[1])
# print(arr[0::2])
# print(arr[-3:-1])

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
# print(arr)
# print(arr[2][1])
# arr[1,1] = 100
# print(arr)

# matrix[row_start:row_end, column_start:column_end]
print(arr[0:2,:])
print(arr[:, 0:2])
print(arr[0:2, 0:2])
print(arr[:, 1])

[[10 20 30]
 [40 50 60]]
[[10 20]
 [40 50]
 [70 80]]
[[10 20]
 [40 50]]
[20 50 80]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print(arr)
print(arr[arr > 50])
print(arr[arr % 3 == 0])

[10 20 30 40 50 60 70 80 90]
[60 70 80 90]
[30 60 90]


In [ ]:
import numpy as np

# vector_row = np.array([1, 2, 3])
# vector_col = np.array([[1], [2], [3]])

# print("Row:")
# print(vector_row)
# print("Col:")
# print(vector_col)

# matrix = np.array([
#     [1,2,3],
#     [4,5,6]
#     ])
# print(matrix)

# matrix1 = np.array([
#     [1,2],
#     [3,5]
#     ])
# matrix2 = np.array([
#     [1,2],
#     [3,5]
#     ])

# print("Matrix 1:")
# print(matrix1)
# print("Matrix 2:")
# print(matrix2)

# result = matrix1+matrix2
# # mul = np.dot(matrix1, matrix2)
# mul = (matrix1 @ matrix2)

# print("Sum: ", result)
# print("Dot prod:", mul)

In [ ]:
# Sparse: mostly elements 0, dense opposite
import numpy as np
from scipy import sparse

matrix = np.array(
    [
        [0, 0, 5],
        [0, 1, 0],
        [2, 0, 0],
    ]
)

print("Original Matrix:")
print(matrix)

matrix_sparse = sparse.csr_matrix(matrix)

print("Sparse Matrix:")
print(matrix_sparse)

Original Matrix:
[[0 0 5]
 [0 1 0]
 [2 0 0]]
Sparse Matrix:
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	5
  (1, 1)	1
  (2, 0)	2


In [ ]:
# import numpy as np

# arr1 = np.array([
#     [1,2,3],
#     [3,5,6],
# ])
# print(arr1[1,1])

import numpy as np

arr1 = np.array([
    [1 ,2 ,3],
    [3 ,5 ,6],
    [7 ,8 ,9],
])
# print("=>\n" ,arr1[0:1 ,0:])
# print("=>\n" ,arr1[1:2 ,0:])
# print("=>\n" ,arr1[: ,0:1])

print(np.min(arr1))
print(np.max(arr1))
print(np.min(arr1, axis=0)) # for col
print(np.max(arr1, axis=1)) # for row


1
9
[1 2 3]
[3 6 9]


In [4]:
import numpy as np

matrix = np.array([
     [1 ,2 ,3],
     [4 ,5 ,6],
     [7 ,8 ,9]
    ])
print(matrix)

add_100 = lambda i: i+100

vectorize_add_100 = np.vectorize(add_100)

print(vectorize_add_100(matrix))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [9]:
import numpy as np

matrix = np.array([
     [1 ,2 ,3],
     [4 ,5 ,6],
     [7 ,8 ,9]
    ])
print(matrix)
print("Max: ",np.max(matrix))
print("Max: ",np.min(matrix))

# axis 0 and 1 give max and min in row and col
print("Max: ",np.max(matrix, axis=0))
print("Max: ",np.min(matrix, axis=1))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
Max:  9
Max:  1
Max:  [3 6 9]
Max:  [1 4 7]


In [12]:
import numpy as np

matrix = np.array([
     [1 ,2 ,3],
     [4 ,5 ,6],
     [7 ,8 ,9]
    ])
print(matrix)

# Mean       → Average
# Variance   → Spread²
# Std        → √Variance

print(np.mean(matrix))
print(np.std(matrix))
print(np.var(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
2.581988897471611
6.666666666666667


In [17]:
import numpy as np

matrix = np.array([
     [1 ,2 ,3],
     [4 ,5 ,6],
     [7 ,8 ,9],
     [10 ,11 ,12],
    ])
print(matrix)
#while reshaping old(rows*col)=new(rows*col)

print(matrix.reshape(3,4))
print(matrix.reshape(6,2))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
